import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'admin',
      email: 'admin@email.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'user1',
      email: 'user1@email.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  designs: [
    {
      // _id: '1',
      name: 'Crash Randicoot',
      slug: 'crash-randicoot',
      category: 'Video Games',
      image: '/images/crash-randicoot.jpg',
      price: 85,
      printToOrder: true,
      style: 'water colour',
      rating: 0,
      numReviews: 0,
      description:
        'water colour style crash themed characters wallpaper pattern.',
    },
    {
      // _id: '2',
      name: 'Monkey Kong Village',
      slug: 'monkey-kong-village',
      category: 'Video Games',
      image: '/images/monkey-kong-village.jpg',
      price: 85,
      printToOrder: false,
      style: 'computer generated',
      rating: 0,
      numReviews: 0,
      description: '3D video game style monkey kong village.',
    },
    {
      // _id: '3',
      name: 'Mario Watercolour Pattern',
      slug: 'mario-water-colour pattern',
      category: 'Video Games',
      image: '/images/mario-watercolour-pattern.jpg',
      price: 85,
      printToOrder: true,
      style: 'water colour',
      rating: 0,
      numReviews: 0,
      description:
        'water colour style mario themed characters wallpaper pattern.',
    },
    {
      // _id: '4',
      name: 'Dark City Heroes',
      slug: 'dark-city-heroes',
      category: 'Comics and Popular Culture',
      image: '/images/dark-city-heroes.jpg',
      price: 85,
      printToOrder: true,
      style: 'comic book art',
      rating: 0,
      numReviews: 0,
      description:
        'comic book style heroes in a city on a dark and rainy night.',
    },
    {
      // _id: '4',
      name: 'Arcade Fighter',
      slug: 'arcade-fighter',
      category: 'Video Games',
      image: '/images/arcade-fighter.jpg',
      price: 85,
      printToOrder: true,
      style: 'retro 90s',
      rating: 0,
      numReviews: 0,
      description:
        'arcade fighters gearing up for the street fight of their lives.',
    },
    {
      name: 'Space Pac',
      slug: 'space-pac',
      category: 'Video Games',
      image: '/images/space-pac.jpg',
      price: 85,
      printToOrder: true,
      style: 'wallpaper pattern',
      rating: 0,
      numReviews: 0,
      description:
        'Retro arcade style space invaders in a pac man style maze wallpaper pattern.',
    },
    {
      name: 'Pirate Adventure',
      slug: 'pirate-adventure',
      category: 'Cartoons and Animation',
      image: '/images/pirate-adventure.jpg',
      price: 85,
      printToOrder: true,
      style: 'computer generated',
      rating: 0,
      numReviews: 0,
      description:
        'cartoon, animation style pirate adventure on the seven seas.',
    },
    {
      name: 'Invincible Super Heroes',
      slug: 'invincible-super-heroes',
      category: 'Comics and Popular Culture',
      image: '/images/invincible-super-heroes.jpg',
      price: 85,
      printToOrder: true,
      style: 'comic book art',
      rating: 0,
      numReviews: 0,
      description: 'Invincible super heroes battle it out in new york city.',
    },
    {
      name: 'Coral Shipwreck',
      slug: 'coral-shipwreck',
      category: 'Traditional Art',
      image: '/images/coral-shipwreck.jpg',
      price: 85,
      printToOrder: true,
      style: 'water colour painting',
      rating: 0,
      numReviews: 0,
      description:
        'A mysterious shipwreck surrounded by a brightly coloured coral reef.',
    },
    {
      name: 'Jungle Kook',
      slug: 'jungle-kook',
      category: 'Cartoons and Animation',
      image: '/images/jungle-kook.jpg',
      price: 85,
      printToOrder: true,
      style: 'computer generated',
      rating: 0,
      numReviews: 0,
      description: 'A jungle boy, dancing with his bear friends.',
    },
    {
      name: 'Jungle Watercolour',
      slug: 'jungle-watercolour',
      category: 'Traditional Art',
      image: '/images/jungle-watercolour.jpg',
      price: 85,
      printToOrder: true,
      style: 'water colour painting',
      rating: 0,
      numReviews: 0,
      description:
        'A water colour style jungle scene with foliage, vines, birds and flowers.',
    },
    {
      name: 'Plumber Pipes',
      slug: 'plumber-pipes',
      category: 'Video Games',
      image: '/images/plumber-pipes.jpg',
      price: 85,
      printToOrder: false,
      style: 'computer generated',
      rating: 0,
      numReviews: 0,
      description: '3D video game style plumber and his pipes.',
    },
  ],
};

export default data;
